# Site settings
title: LiuXin
subtitle: stay hungry, stay foolish 
email: 15514657777@163.com
description: 求知若渴 虚怀若愚 <br /> stay hungry, stay foolish.
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: liuxin
street_address: 
city: Waterloo
state: Ontario
zip_code: 
country: Canada
phone: (1)-226-505-6868


# Social settings
facebook_url: https://www.facebook.com/profile.php?id=100009585159226
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/harryliuxin/
linkedin_url: https://www.linkedin.com/in/xin-liu-868501134
pinterest_url:
video_url: http://www.miaopai.com/u/wxsso_p4mslofx14
twitter_url: 
weibo_url: http://weibo.com/u/2377304267

# Build settings
markdown: kramdown

sass:
  style: compressed
